### ISSUE TITLE
build issues

### ISSUE THREAD

**Issue by sunyiven** [iiordanov/remote-desktop-clients#116]
Hello iiordanov,
when I run the script ./eclipse_projects/bVNC/prepare_project.sh $PROJECT $ANDROID_NDK,then it shows `ant release`
`Buildfile:build.xml does not exist!`
`Build faild`
`make:***[build-java] Error 1`
`Failed:make(line 557)`

**Comment by iiordanov** [comment]
Does it say which project is missing the file? (There are a bunch of
projects that are built to assemble the client).

Thanks!
Iordan

**Comment by sunyiven** [comment]
just aSPICE.
this is part of log 

[arm64-v8a] Install        : libsqlcipher.so => jni/libs64/arm64-v8a/libsqlcipher.so
install -p /home/user/Downloads/remote-desktop-clients-3.9.7/eclipse_projects/Opaque/jni/libs/deps/android-database-sqlcipher/obj/local/arm64-v8a/libsqlcipher.so /home/user/Downloads/remote-desktop-clients-3.9.7/eclipse_projects/Opaque/jni/libs/deps/android-database-sqlcipher/jni/libs64/arm64-v8a/libsqlcipher.so
/home/user/android-ndk-r13b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-strip --strip-unneeded  /home/user/Downloads/remote-desktop-clients-3.9.7/eclipse_projects/Opaque/jni/libs/deps/android-database-sqlcipher/jni/libs64/arm64-v8a/libsqlcipher.so
make[1]: Leaving directory `/home/user/Downloads/remote-desktop-clients-3.9.7/eclipse_projects/Opaque/jni/libs/deps/android-database-sqlcipher/jni'
ant release
Buildfile: build.xml does not exist!
Build failed
make: *** [build-java] Error 1
Failed: make (line 557)
~/Downloads/remote-desktop-clients-3.9.7/eclipse_projects/bVNC ~/Downloads/remote-desktop-clients-3.9.7
Android NDK: ERROR:jni/src/Android.mk:sqlcipher: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that jni/src/../libs/deps/android-database-sqlcipher/libs/x86/libsqlcipher.so exists  or that its path is correct   
/home/user/android-ndk-r13b/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
Error: Project folder 'jni/libs/deps/FreeRDP/client/Android/Studio/freeRDPCore/src/main' is not a valid directory.
~/Downloads/remote-desktop-clients-3.9.7



Thank you

**Comment by iiordanov** [comment]
Hi,

I believe with the latest commit to master the issue should be fixed.
Android ask was refusing to create a build.xml file for FreeRDP without
having android target specified on the command line.

Iordan

On Oct 18, 2017 2:17 AM, "sunyiven" <notifications@github.com> wrote:

just aSPICE.
this is part of log

[arm64-v8a] Install : libsqlcipher.so => jni/libs64/arm64-v8a/
libsqlcipher.so
install -p /home/user/Downloads/remote-desktop-clients-3.9.7/eclipse_
projects/Opaque/jni/libs/deps/android-database-sqlcipher/
obj/local/arm64-v8a/libsqlcipher.so /home/user/Downloads/remote-
desktop-clients-3.9.7/eclipse_projects/Opaque/jni/libs/deps/
android-database-sqlcipher/jni/libs64/arm64-v8a/libsqlcipher.so
/home/user/android-ndk-r13b/toolchains/aarch64-linux-
android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-strip
--strip-unneeded /home/user/Downloads/remote-desktop-clients-3.9.7/eclipse_
projects/Opaque/jni/libs/deps/android-database-sqlcipher/
jni/libs64/arm64-v8a/libsqlcipher.so
make[1]: Leaving directory `/home/user/Downloads/remote-
desktop-clients-3.9.7/eclipse_projects/Opaque/jni/libs/deps/
android-database-sqlcipher/jni'

ant release
Buildfile: build.xml does not exist!
Build failed

make: *** [build-java] Error 1
Failed: make (line 557)
~/Downloads/remote-desktop-clients-3.9.7/eclipse_projects/bVNC
~/Downloads/remote-desktop-clients-3.9.7
Android NDK: ERROR:jni/src/Android.mk:sqlcipher: LOCAL_SRC_FILES points to
a missing file
Android NDK: Check that jni/src/../libs/deps/android-
database-sqlcipher/libs/x86/libsqlcipher.so exists or that its path is
correct
/home/user/android-ndk-r13b/build/core/prebuilt-library.mk:45: *** Android
NDK: Aborting . Stop.
Error: Project folder 'jni/libs/deps/FreeRDP/client/
Android/Studio/freeRDPCore/src/main' is not a valid directory.
~/Downloads/remote-desktop-clients-3.9.7

Thank you

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/iiordanov/remote-desktop-clients/issues/116#issuecomment-337471269>,
or mute the thread

**Comment by sunyiven** [comment]
Okay，Thank you very much
