### ISSUE TITLE
The audio can only play for a few seconds 

### ISSUE THREAD

**Issue by TopLuck** [iiordanov/remote-desktop-clients#181]
On the spice, the audio can only play for a few seconds and then disappear. I try to pause and play again. The same situation happened. Is there any good solution? thank you

**Comment by JosephZhou2012** [comment]
we got the same problem. Seems opus codec doesn't work correctly.

**Comment by iiordanov** [comment]
I've seen this happen when there is video and audio playing simultaneously and the SPICE library decides to cut audio due to underruns (not enough CPU or bandwidth or both). I've found that if I play audio alone it works, therefore so far, I've chalked it up to the SPICE library not working quickly enough on certain Android devices. If you think this is not the case, I suggest we ask the SPICE mailing list for help https://lists.freedesktop.org/mailman/listinfo/spice-devel. You can cc me on the discussion as well.

Thanks!
iordan

**Comment by wintli** [comment]
I've also encountered this similar case: I just only play audio, it works well at the beginning of a few seconds, and then  become  noisy, and then disappear, and after serveral seconds, sounnd appear again~ anyone had solved this case? thanks a lot if any comments!
