### ISSUE TITLE
aSpice on Chromebook, washed out colors, looks like 8 bit

### ISSUE THREAD

**Issue by erenoglu** [iiordanov/remote-desktop-clients#190]
I'm trying aSpice on my chromebook. It can connect just fine using Spice protocol, but the colors are washed out. It's like there's a grey filter on the screen.
When I look at display properties, it claims the QXL video card is 8 bit.
aSpice own window looks dark as well even in its menu bars. 
Linux client on the same system works well.

**Comment by iiordanov** [comment]
And does this happen on Android or just on the Chromebook? I don't even own a Chromebook, and I don't even want people to use my apps on the Chromebooks, but here we are :).

Can you send me a screenshot by email? Can you also include the output of "Copy Logcat"?

I'll try and see if there is something out of ordinary reported in the log.

**Comment by erenoglu** [comment]
Hi, here are the screenshots and logcat. 

In one screenshot, you can already see the washed out brownish colored user interface of aSpice. In other one, which is a Windows 10 with black background, you can also see that background is not actually black, and you can see in color palette that colors are strange.
[aspice-logcat.txt](https://github.com/iiordanov/remote-desktop-clients/files/4561436/aspice-logcat.txt)
![Screenshot 2020-05-01 at 01 10 25](https://user-images.githubusercontent.com/2230575/80761276-4d112a00-8b4b-11ea-8539-88b581c10950.png)
![Screenshot 2020-05-01 at 01 29 31](https://user-images.githubusercontent.com/2230575/80761283-50a4b100-8b4b-11ea-93c7-3322831f7a16.png)

**Comment by Cerlancism** [comment]
Same color range reduction happens on Android (Samsung Dex) after pressing a hardware keyboard key. I have tried different servers which as TightVNC and TigerVNC. This didn't happen on another android client called Remote Desktop Manager.

**Comment by bubnikv** [comment]
It looks like https://github.com/iiordanov/remote-desktop-clients/issues/223

**Comment by iiordanov** [comment]
It turned out to be Android not obeying its own API call that tells it a bitmap has no alpha channel.

https://developer.android.com/reference/android/graphics/Bitmap#setHasAlpha(boolean)

I had to start setting the alpha channel to 0xFF for colors to not appear washed out even when setHasAlpha is is called with false.

The fix is out in Beta (make sure you have v5.0.4_115048 in Advanced Settings at the bottom when editing a connection) or install this:

https://github.com/iiordanov/remote-desktop-clients/releases/download/v5.0.4/freeaSPICE-v5.0.4_8-final.apk

**Comment by juergenalbert** [comment]
Thanks for fixing this issue!
Hope the fix soon finds its way to Opaque.

**Comment by iiordanov** [comment]
If you join the Beta for Opaque (through Google Play) you can have the fix
right away.
