### ISSUE TITLE
Problem with newest Opaque

### ISSUE THREAD

**Issue by Smookydope** [iiordanov/remote-desktop-clients#202]
With the new Opaque 1.5.2 i can't connect to my Proxmox VM with the ID 100. All others VM's like 101, 102 and 103 are fine. When i connect to ID 100 the screen are black and the vm crash. With Opaque 1.5.1 all was fine. Where can i find Opaque 1.5.1 apk ?

**Comment by iiordanov** [comment]
Hi,

I do not distribute APK files of Opaque separately from Google Play.

I looked at what changed between the versions and I didn't spot anything
that would single out the VM with ID 100! I suspect that the VM crash
causes Opaque to quit, but I can't find any crash logs in Google Play
whatsoever (which is suspicious in and of itself, my app can't be that
stable...) There is one ANR log, which means some app logs are making it to
me, but your crash log is definitely not.

What is your PVE version? What are you running on the first VM? What
happens if you run the same OS on a slot other than 100?

Can you capture and send me (personally of course) the logcat from Opaque
when it crashes? You can access the functionality from the Menu after
disconnection or after you relaunch the app (if it crashes out of the app).

Cheers and thanks!
Iordan

**Comment by Smookydope** [comment]
Hi Iordan.
Thx for your fast response.
I test it at the next weekend what happens when i change the vm to an other id. Sry but i have not much time. After that i tell you what happens and when the problem persist i send you the logcat.
The problem vm with id 100 is a windows server 2019. On id 101 runs a other windows server 2019 without problems but with other settings. On id 102 and 103 runs two debian systems without problems too. The Proxmox server is a up2date server (6.1-8). 
Before update Opaque from 1.5.1 to 1.5.2 all was fine and i never had a problem with your nice apps.
Thx for your help

Greetings

Smooky (Marcel)

**Comment by iiordanov** [comment]
Hey Smooky, I could not reproduce this issue at all on my Proxmox test systems. Please reopen if it's still an issue and you can give more detail about what causes it. Thanks!
