### ISSUE TITLE
Does BVNC support tigervnc connections?

### ISSUE THREAD

**Issue by JanuszChmiel** [iiordanov/remote-desktop-clients#213]
I have recently tried to use Tigervnc on ArchLinux. I controll it by using provided vncserver script. Vncserver require user to setup password, so I have done that. But unfortunately for Me, BVNC refuses to connect. I Am getting message that something is not supported by Android and dialog window contain advice which option should I add when running X11vnc. Or gnome. Please, how complex would be to extend Bvnc so also Tigervnc could be supported? Or is it possible to type some option so it will be possible to login with yours client? Yours client is The onlyone which support hot keys for Orca screen reader so excellently. I can press CAPSLOCK and hold it and using other letters such as u or j. Every other available VNC clients on GOogle Play do not allow Me to control Orca by using Insert or Capslock. Some VNC clients even do not send The right info to Orca so screen reader can not detect, which key have been pressed.

**Comment by iiordanov** [comment]
Hi,

I am guessing your config enables AnonYLS which uses anonymous Diffie
Hellman Ciphers.

This is not currently supported on Android because Google removed all such
Ciphers from the Operating system itself past a certain version of Android.

For a supported setup, please see these previous support discussions and
links from them.

https://groups.google.com/forum/#!searchin/bvnc-ardp-aspice-opaque-remote-desktop-clients/x509%7Csort:date/bvnc-ardp-aspice-opaque-remote-desktop-clients/stKOUYH67LU/69nz3TgPEAAJ

Please let me know how you fared with the x509 certificate setup. It's more
secure than AnonTLS anyway.

Thanks!
iordan

**Comment by iiordanov** [comment]
Please reopen this issue if you were unable to work around your issues.

**Comment by iiordanov** [comment]
AnonTLS support was added to bVNC in v5.0.9 and newer versions.
