### ISSUE TITLE
Very bright screen output

### ISSUE THREAD

**Issue by Dirk-LG** [iiordanov/remote-desktop-clients#239]
Dear developer,

I'm using "bVNC Free v5.0.3" on an Android device, and output the 24bpp display via USB-C adapter (HDMI) to a TV set.
Compared to the output of any other VNC client, or standard Android output, bVNC is very bright. It might be a gamma value of about 1.6, or an increased white level? Moreover, the darker areas of the attached image incl. the heaven show JPEG artifacts.

Could this please fixed, or how can it be changed in the settings, or in the code?

Thanks a lot
Dirk

![DiaMag17_125](https://user-images.githubusercontent.com/52800761/101547438-872c8f00-39aa-11eb-808e-62668c8ac9a2.jpg)

**Comment by iiordanov** [comment]
Hi Dirk,

I see absolutely no evidence that there is any fault with bVNC whatsoever. The app does not tweak brightness on the device and it does not change the color values of the pixels of the remote display.

The JPEG artifacts are definitely because of the TightVNC encoding, and it is on the roadmap of the app to provide control over the level of compression. There is already an issue to track that: https://github.com/iiordanov/remote-desktop-clients/issues/58
