### ISSUE TITLE
Android Spice USB redirection

### ISSUE THREAD

**Issue by HeartHappy** [iiordanov/remote-desktop-clients#281]
After Spice remote under the Android system, the USB cannot be redirected to the desktop after inserting the USB

**Comment by nkotixwolf** [comment]
USB redirection would be a new feature request.
I have added this to the development backlog.
Updates will be posted here once selected for development.

**Comment by bboydanyel27** [comment]
Não consigo conectar o pendrive via otg não o reconhece

**Comment by mjuned47** [comment]
> USB redirection would be a new feature request.
> I have added this to the development backlog.
> Updates will be posted here once selected for development.

What's update on this?

**Comment by nkotixwolf** [comment]
mjuned47 this is quite far from priority right now due to other outstanding issues and the amount of time required to add this feature and maintain it. 

This requires for us to entirely rework USB support due to major changes in Android since the original feature was implemented in Android 4.2. Hence this feature is a major time investment for us which is making it less viable to implement at the moment.
For more questions, email support@morpheusly.com

**Comment by iiordanov** [comment]
Linking the fix for this issue here: https://github.com/iiordanov/remote-desktop-clients/issues/326
