### ISSUE TITLE
Bug on trackpad mode. Mouse cursor teleporting.

### ISSUE THREAD

**Issue by ghost** [iiordanov/remote-desktop-clients#287]
When i move the cursor and holding the keyboard. the mouse cursor is teleporting. fix it dude now! bvnc

**Comment by iiordanov** [comment]
I cannot reproduce this issue. Could you please give more details on what button should be held on the keyboard, whether the keyboard is physical or soft keyboard. Exact instructions for reproducing the bug are needed!

If the issue is still present and I should reopen the issue, please let me know.
