### ISSUE TITLE
bVNC Allow software keyboard to be opened while using a physical keyboard

### ISSUE THREAD

**Issue by ThePhxRises** [iiordanov/remote-desktop-clients#305]
On the new Titan Pocket, the software keyboard is required to enter characters the physical keyboard does not have, including numbers when the Alt key is controlled by bVNC. However, attempting to open the software keyboard simply has it close immediately, presumably because the app sees a physical keyboard attached and assumes it's unnecessary.

**Comment by iiordanov** [comment]
Hey, I added an experimental option to long-tap the keyboard button to force the soft keyboard to show.

Could you please try this version and see if it does what we want?

https://github.com/iiordanov/remote-desktop-clients/releases/download/v5.1.2/freebVNC-v5.1.2_2-final.apk

**Comment by iiordanov** [comment]
@ThePhxRises as I was working on a related piece of functionality (to show extended software keyboards for devices with hardware keyboards) it turned out that there is a system provided toggle to allow both the hardware and software keyboard to be shown. Furthermore, to force such functionality from an Android program appears to be near impossible or completely impossible, probably since it's supposed to be a system-governed function. Please let me know if your understanding is different.
