### ISSUE TITLE
aRDP : Connection Failed

### ISSUE THREAD

**Issue by handgun50** [iiordanov/remote-desktop-clients#316]
Can't connect with pretty simple rdp settings
Android lollipop 5.1 Oppo A39

![Screenshot_2021-11-20-00-59-00-37](https://user-images.githubusercontent.com/8114257/142711729-54888717-6d0d-4096-8928-490c4dc7a6ed.png)
![Screenshot_20211120093613](https://user-images.githubusercontent.com/8114257/142711740-c0600afb-cb61-4976-a1e0-4ff77189124b.png)

**Comment by iiordanov** [comment]
Hey!

Yeah, this is a missing library. Are you building the app yourself or just downloading and installing from Google Play?

Does any release from here work?
https://github.com/iiordanov/remote-desktop-clients/releases

Thanks!
iordan

**Comment by handgun50** [comment]
Download from playstore.

I tried 5.0.5.9 and 5.0.3.9. Both not work. It has same error

**Comment by iiordanov** [comment]
Hey, the closest I can get to your device is a Samsung Galaxy Nexus running 6.0.1. It also sports the arm architecture as I believe your Oppo does. I installed the latest Beta from Google Play and it works just fine. So strange! It seems like as it is installing something goes missing because the arm libraries are definitely there in the apk file.

Does one of those significantly older releases work:

https://github.com/iiordanov/remote-desktop-clients/releases/tag/v3.8.8

Thanks!

**Comment by handgun50** [comment]
Version 3.8.8.4 works

I also did try higher version. The highest version I can get working is 5.0.3.6. From 5.0.3.7 it throws the same error.

But actually I feel that version 3.8 feels more faster in term of updating screen pixel than version 5

**Comment by iiordanov** [comment]
Closing since we found a workaround for your issue.
