### ISSUE TITLE
x2goclient

### ISSUE THREAD

**Issue by Jcfunk** [iiordanov/remote-desktop-clients#353]
Could you please create a client for X2go protocol.
https://code.x2go.org/gitweb?p=x2goclient.git;a=summary

This would be great,  there is no android client for this.
You would be the first to make it. The other clients you have made are great.

**Comment by iiordanov** [comment]
I looked into this a while back and was deterred by the complexity involved.

It seems https://code.google.com/archive/p/android-xserver/source/default/source or http://www.jcraft.com/weirdx/ could be or another project could be used to run an X server on Android. As far as I remember running a local X server would be needed to have an Android NX Client. Combined with libnx it could be used to create a client. However at that point, it seems to me like the UI of the application would be the local X server rather than this project's UI, which makes the whole objective of reusing this project's UI pointless. Please let me know if I am off on this point.

Furthermore, I felt like with the rise of Wayland, X server and NX as a protocol is going to become obsolete in the long run. Please correct me if I'm wrong on that point as well.
