### ISSUE TITLE
Watch Netflix in desktop-version Chrome on Android - best solution? aRDP, aSpice, or Opaque?

### ISSUE THREAD

**Issue by ShiroiKuma0** [iiordanov/remote-desktop-clients#390]
Hi:

I"m looking for a solution to the following problem - I'd like to use a desktop version Linux or Windows Chrome to watch Netflix in it - locally on my Android phone. The phone is high-end - Samsung Fold 4. The reason for wanting to do this - use languagereactor.com Chrome extension - enables dual subtitles in Netflix for language learning.

The possibilities are: Linux i386 chroot using ExaGear - and then aRDP. Or QEMU i386 or x64 image with Windows 7. 

The Linu chroot I have setup, bVNC works great - but no sound. So aRDP? Any pointers on how to set it up for this local access?

Or is the way to go through QEMU and aSpice or Opaque? How to set it up?

The question is what would be fast enough that it would enable the sound and video without stuttering?

**Comment by iiordanov** [comment]
> The Linu chroot I have setup, bVNC works great - but no sound. So aRDP? Any pointers on how to set it up for this local access?

Is it impossible to enable the chrooted OS to play sound directly on the device somehow? Then, the remote desktop doesn't have to carry the sound itself.


As far as aRDP, I am not sure whether that will be fast enough, since from my observations, the RDP protocol isn't quite as optimized for fast framerates. That being said, I've seen people set up xrdp with sound being transferred and I've watched videos over xrdp (but never needed to set up sound).

QEMU-kvm with aSPICE doesn't sound possible, and a quick look doesn't show anybody attempting it. There is no KVM module for Android devices, as far as I know, unless it is your own custom Android OS with your own custom Linux kernel.

Opaque is specifically geared to connecting to Proxmox and oVirt, so it's not a good pick.
