### ISSUE TITLE
Portuguese Keyboard issue

### ISSUE THREAD

**Issue by peufemia** [iiordanov/remote-desktop-clients#392]
Sending these sequence "áàãâ '? <> -_" in "Send Text" option, with and witout "unicode input" selected the result is the same, that is OK! The characters apears as it should!

If I repeat the same sequence directly in keyboard WITH "unicode input" selected:
"a´`aa~^a '? <> -_"

If I repeat the same sequence directly in keyboard WITHOUT "unicode input" selected:
"áàãâ -_ ++ '?"

What I verify is:
if  unicode IS selected the key "'?", "-_" and "<>"  are OK and accent characters are scrambled.
if unicode IS NOT selected the keys "-_" and "'?" are switched, the key "<>" became "++" and accent characters are OK.

Thanks.

Previouse email for context:

"
_What happens if you "Send Text" and send the above sequences with and
without unicode input selected?

It may be better to continue this discussion in a new bug-report for
the app at https://github.com/iiordanov/remote-desktop-clients/issues?

Thanks!
iordan

On Sat, Nov 12, 2022 at 8:34 AM Paulo Eufémia <[paulo.eufemia@gmail.com](mailto:paulo.eufemia@gmail.com)> wrote:
>
> Hi,
> I have a Samsung TAB S7 FE with official Portuguese keyboard cover and have little issues with special character when connecting to a Windows 10 machine.
>
> If "Unicode input" is selected, everything is OK except when using accents like " ´ ` ~ ^ ", for example " á à ã â ".
> Pressing the respective keys in sequence like the example above produces " a ´`a a ~^a "
>
> If "Unicode input" is NOT selected, those special characters work OK, but 3 others keys are misplaced or exchanged: "<>",  "'?",  "-_".
> Pressing the keys in sequence like the example above (the keys have printed the above value) produces "++",  "-_",  "'?".
> (These 3 keys were pressed each one in same sequence: one touch for first character of key and shift+touch for second character of key)
>
> This issue have any kind of solution?
>
> Thanks.
>
>
>
> --_
"

**Comment by iiordanov** [comment]
I tested what you described, and here is my setup and my observations. I connected and configured a (French layout) keyboard on my Android device as Portuguese layout keyboard. This keyboard does have the physical key for < and >, so I can test those as well. I was able to type all the characters you reported in an Android text box. I have to type the accents before the letter.

I connected to both a Windows 11 box and a Windows 10 box for testing. I configured Windows to have Portuguese (Portugal) layout and I switched to that layout When it was with English layout, input was completely incorrect.

Windows 10:
With both unicode input enabled and disabled, I cannot seem to type any accents whatsoever - with one stroke, they don't appear at all. With two strokes they do appear as regular characters rather than dead keys. On the other hand, all of <>?'_- are typed correctly.

Windows 11:
With both unicode input enabled and disabled, I am able to type all accents correctly!  With two strokes they also appear as regular characters. On the other hand. all the remaining characters are incorrect. <> are ++, and ?' are switched with _-.

This difference in behavior between Windows versions is very puzzling. It seems that they recognized and fixed something with the dead accents in Portuguese between Windows 10 and 11. However while they did that, they broke <> and switched ?' and _-. Given the totally contradictory and different behavior between Windows versions, I am not sure I'm in a position to change anything in aRDP without breaking things.
