### ISSUE TITLE
Opaque build does not install on Android

### ISSUE THREAD

**Issue by jvinolas** [iiordanov/remote-desktop-clients#399]
The Opaque apk is 125MB size and when trying to install on android device, at the end, it says "could not install".

- Android 11 RKQ1.201004.002

Any tips on this?

**Comment by iiordanov** [comment]
Why do you think it's because of the size? Is the device close to being out
of space? The app requires many libraries and needs to support four
architectures (for google play requirements) and that is why the APK is
125mb. There are probably things that can be done to reduce the size, such
as deleting the unneeded architectures, i e. If building for an arm64
device, find and delete the libs for x86, x86_64 and armv7.

**Comment by jvinolas** [comment]
Sorry, I didn't mean the size was a problem, the problem is not installing it at the end. Should install on that android?

**Comment by iiordanov** [comment]
It's possible this was because you already had Opaque from the store installed.
