### ISSUE TITLE
Issue with bVNC Pro on iOS controlling Windows machine via PiKVM

### ISSUE THREAD

**Issue by c0dyhi11** [iiordanov/remote-desktop-clients#411]
Hello, 

I have posted about this on [Reddit](https://www.reddit.com/r/pikvm/comments/10emyf1/bvnc_controlling_windows_pc_does_a_clickdrag/) as well as on what looks to be the [GitLab for the iOS App](https://gitlab.com/iiordanov/remote-desktop-clients-ios/-/issues/1). But maybe this is the proper place to post this.

You can see the video on Reddit with the issues but in a nut shell:

I’m trying to control a simple website. But every time I click with bVNC on iOS. I get a “click and drag” instead of a single click. This may be an issue with how PiKVM's VNC translation layer works, but this does not happen using the Web UI for PiKVM.

I have paid for bVMC Pro on the Apple store specifically for this feature. 
Has anyone gotten PiKVM control-able from the iOS app?

Thank you,
Cody Hill

**Comment by iiordanov** [comment]
Hi Cody, Thanks for opening this issue. I definitely want to determine what the root cause is. Can you tell me something more about your setup?

1) What device do you have bVNC Pro for iOS on?
2) Do you use an external mouse or the screen of the device?
3) Do you have the latest version of the software from the App Store? Can you double-check what version the App store tells you you're running?

A few additional questions:
4) Have you tried other standalone VNC software (other than the web interface) or just bVNC Pro so far?
5) Are you sure this is a click drag and not a double-click or something crazier?
Maybe capturing one instance of the weird click with a page like https://www.unixpapa.com/dblclick.html would give us some idea?

I couldn't find a good tool for Windows like xev that would give us more info. You wouldn't happen to be able to boot into an Ubuntu usb sick on this machine to run xev, would you?

**Comment by c0dyhi11** [comment]
Thanks for the reply. 

1. I have bVNC Pro for iOS running on: iPhone 12 Pro (256GB)
2. There is no external mouse connected to my iPhone or the Intel NUC Pi KVM is controlling
3. The App Store version shows (1.0.17)
4. I just recently tested this with TigerVNC and everything works as expected.
5. I'm not sure it's a click/drag... vs Double Click. I'm guessing I just click the top blue link that says `test` and here is the output
    * TigerVNC Viewer on Windows:
    ```
    mousedown which=1 button=0
    mouseup which=1 button=0
    click which=1 button=0
    ```
    * bVNC Pro on iOS
        * *(But in order to get a click to register I had to tap the screen a few times in rapid succession as if I was double clicking)*
    ```
    mousedown which=1 button=0
    mouseup which=1 button=0
    click which=1 button=0
    ```
6. Here is a link to Ubuntu 22.04 with `xev` running.
    * https://drive.google.com/file/d/1uA9IsekVjp5S47c9t6x5RyYqW9QmV0I4/view
    * Every time the mouse moves in the white box, I'm doing a single click. I then try a double click and hold to drag and that seems to work, but then I'm stuck in "drag" mode. And I have to triple to quadruple click to get out of it. I'm not sure how to interpret this output, but I hope this helps. 
    
Let me know if there are any other tests you'd like me to run, or if there is a Discord we could get on or something similar, I could give you remote access to this box to see if you have the same issues...

Thank you!

**Comment by c0dyhi11** [comment]
Hello. Any update on this?

**Comment by mdevaev** [comment]
It's a bug from my side. Fixed: https://github.com/pikvm/pikvm/issues/925#issuecomment-1458991351

**Comment by c0dyhi11** [comment]
Awesome! Thanks!. So their should be an update to bVNC on the App Store for this? Is this correct?

**Comment by mdevaev** [comment]
No, you need to update pikvm os.

**Comment by c0dyhi11** [comment]
Got it. Thanks!

**Comment by iiordanov** [comment]
Thanks so much, @c0dyhi11 and @mdevaev!
