### ISSUE TITLE
aSPICE Pro - Resolution seems wrong on iPadOS 

### ISSUE THREAD

**Issue by OptimusPi** [iiordanov/remote-desktop-clients#417]
Device: iPad 8th Gen 
Device resolution: 2160x1620

VM Resolution: (exactly half of iPad resolution) 1080x810

There is a gap around the left, right, and bottom of the screen. Some resolutions do fill this gap though.

Additionally, there seems to be some sort of video buffer left over and there are all sorts of colors left over from either previous session or...? 

![image](https://user-images.githubusercontent.com/16853743/216218209-75cc642f-8f1b-49d4-810b-ce6127441c6b.png)

**Comment by iiordanov** [comment]
Hey, the reason this is happening is that iOS does not report the actual resolution of the device when queried for the size of the "root window". Rather, it reports some device independent values that allow apps to size content in a device-independent manner so (for example) buttons appear proportionately sized on various displays.

I had some logic to scale up from that low device-independent resolution, but had a minimum resolution above which this logic does not fire. I've switched it to scale the resolution up (it's an automatic factor of 1.5 which feels comfortable to me). The fix is in https://gitlab.com/iiordanov/remote-desktop-clients-ios/-/commit/9bfbff8727125a2f6c8ad108753d446581606380

**Comment by iiordanov** [comment]
Please get in touch by email with support _at_ morpheusly _dot_ com if you'd like to beta test this and the other changes.
