### ISSUE TITLE
Redirect sdcard

### ISSUE THREAD

**Issue by benjibasson83** [iiordanov/remote-desktop-clients#460]
Hi,
Although I have checked redirect sdcard I have no access to my local storage through the rdp session.

> It no longer exists in This PC. Check its current location, and try again.
> 
> sdcard sur aFreeRDP-5aaf39

Remote Desktop Connection Disk

Can you please enabled the redirectiob of /storage/emulated/0/
Or let me choose the folder to share.

Cheers

**Comment by iiordanov** [comment]
Hey, thanks for the report. The issue should be fixed in 6281e4f238fc6b087704006500dc3b009bfef16a, and the fixed version was just published to Beta. It is v5.1.2_115128, which is visible under Advanced Settings all the way at the bottom when you edit a connection.

Once you redirect the SDCard, a network drive tsclient shows up. You can copy files there or from there, and then use a File Manager to find the data under Android/data/com.iiordanov.aRDP (or Android/data/com.iiordanov.freeaRDP) in external storage.

Please let me know if something is not working and I'll reopen the bug-report and look into it.
