### ISSUE TITLE
support TlsPort, CaCertPath and CertSubject in SPICE data uri

### ISSUE THREAD

**Issue by jelkosz** [iiordanov/remote-desktop-clients#49]
for use from moVirt, we need this 3 parameters to be part of the data uri. The relevant code should be something like: https://github.com/zyx0225/remote-desktop-clients/commit/5233d9bb5f6434bba97237fd8ea014cf19b14c88

Do you think you could add it to aSPICE?
Thank you!

**Comment by iiordanov** [comment]
Hi, I've added the functionality in an updated v3.7.7. I actually alter:

                               <data android:scheme="vnc" /> 
to:
                               <data android:scheme="spice" /> 

in AndroidManifest.xml at release time, since the AndroidManifest.xml with the code represents bVNC.

Please find a pre-built binary here:

https://github.com/iiordanov/remote-desktop-clients/releases/download/v3.7.7/freeaSPICE-3.7.7-final.apk
