### ISSUE TITLE
bVnc stop working on Android 6.0

### ISSUE THREAD

**Issue by tremrej** [iiordanov/remote-desktop-clients#60]
I'm getting this error:
Connection failed.
Connection to VNC server failed with reason:
[Ljava.lang.StackTraceElement;@c3d2f5dTLS handshake failed
javax.net.ssl.SSLHandshakeException: Handshake failed

The exact same application was working fine in Android 5.1.1 before I upgraded my Nexus 9 to 6.0.
I have the same issue on my Nexus 5.

**Comment by iiordanov** [comment]
This has already been reported and is a known issue. I do not have an Android 6 device yet, but will look into it as soon as i can.                                                                                                                                                                                                                                                                                                                                        --The conscious mind has only one thread of execution.                                                                                                                                                                                                                From: tremrejSent: Thursday, October 15, 2015 00:25To: iiordanov/remote-desktop-clientsReply To: iiordanov/remote-desktop-clientsSubject: [remote-desktop-clients] bVnc stop working on Android 6.0 (#60)I'm getting this error:
Connection failed.
Connection to VNC server failed with reason:
[Ljava.lang.StackTraceElement;@c3d2f5dTLS handshake failed
javax.net.ssl.SSLHandshakeException: Handshake failed

The exact same application was working fine in Android 5.1.1 before I upgraded my Nexus 9 to 6.0.
I have the same issue on my Nexus 5.

—Reply to this email directly or view it on GitHub.

**Comment by iiordanov** [comment]
Bad news, everyone. Looks like Anonymous Diffie Hellman (DH) ciphers were dropped past API 22 (Android 6.0 is API 23). This means that any protocol like the AnonTLS protocol used by Vino 
http://developer.android.com/reference/javax/net/ssl/SSLEngine.html

There is a workaround for x11vnc if you're running it yourself on the command-line. You need to add the "-vencrypt nodh:only -ssl" options. For example, to automatically find/create a session for your user and use VeNCrypt with Anonymous DH disabled, you can use:

x11vnc -create -vencrypt nodh:only -ssl

For Vino server, the only way to work around this server-side is to disable encryption with the following command on the command-line:

gsettings set org.gnome.Vino require-encryption false

I do not see how we can do better for Vino, unfortunately. Client-side, I will probably throw up a message that AnonTLS is no longer supported if I find the app is running on Android 6 and newer.

**Comment by JohnDelay2** [comment]
Dear Iordan. First I´d like to thank you for sharing bVNC with the world. I suppose the a.m. problem (by tremrej) isn´t related to Android version, because I get exactly the same error message on my Lenovo K3 Note with Android 5.1, trying to connect to a VeNCrypt Server on my Win 7 Home machine. Did you meanwhile figure out, what else could cause this issue? Kind regards, Ingo

**Comment by bwsb88dev** [comment]
Dear Iordan,
Thanks for a nice wonderful android app - bVNC. Working fine until Android 6.  I am used to connect to my Linux desktop via Vino using SSH secure connection.  You mentioned switching off encryption on my Vino Server. In that case would I still be protected by SSH? Thanks again.
Warmest Regards,
Bob

**Comment by iiordanov** [comment]
Yes!Cheers, iordan                                                                                                                                                                                                                                                                                                                                         --The conscious mind has only one thread of execution.                                                                                                                                                                                                                From: bwsb88devSent: Sunday, March 19, 2017 07:41To: iiordanov/remote-desktop-clientsReply To: iiordanov/remote-desktop-clientsCc: iiordanov; State changeSubject: Re: [iiordanov/remote-desktop-clients] bVnc stop working on Android 6.0 (#60)Dear Iordan,
Thanks for a nice wonderful android app - bVNC. Working fine until Android 6.  I am used to connect to my Linux desktop via Vino using SSH secure connection.  You mentioned switching off encryption on my Vino Server. In that case would I still be protected by SSH? Thanks again.
Warmest Regards,
Bob

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iiordanov/remote-desktop-clients","title":"iiordanov/remote-desktop-clients","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iiordanov/remote-desktop-clients"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bwsb88dev in #60: Dear Iordan,\r\nThanks for a nice wonderful android app - bVNC. Working fine until Android 6.  I am used to connect to my Linux desktop via Vino using SSH secure connection.  You mentioned switching off encryption on my Vino Server. In that case would I still be protected by SSH? Thanks again.\r\nWarmest Regards,\r\nBob"}],"action":{"name":"View Issue","url":"https://github.com/iiordanov/remote-desktop-clients/issues/60#issuecomment-287610755"}}}

**Comment by frispete** [comment]
Hi Iordan, 
being an innocent user of TigerVNC and bVNC Pro, I got caught in the crossfire of this [issue](https://github.com/TigerVNC/tigervnc/issues/507#issuecomment-326752301) today.
Before I dive into the VeNCrypt and anonymous TLS implementations, it would be nice, if you participate in the discussion, since your baby is concerned. 

If I interpret the situation correctly, Google deactivated any of the anonymous TLS cipher variants. 
How hard would it be to base bVNC on a third party TLS lib like GNUTLS?

Loosing VeNCrypt encryption support in many scenarios is a real pity for bVNC, isn't it?

**Comment by iiordanov** [comment]
https://github.com/bcgit/bc-java/issues/1129
