### ISSUE TITLE
how to build aspice in Android studio 

### ISSUE THREAD

**Issue by wangcheng711** [iiordanov/remote-desktop-clients#62]
hi，how to build aspice in Android studio in windows 7

**Comment by iiordanov** [comment]
i do not think it is possible tocuse android studio without modifications to aSPICE because of the sqlitegen eclipse plugin dependency.                                                                                                                                                                                                                                                                                                                                        --The conscious mind has only one thread of execution.                                                                                                                                                                                                                From: wangcheng711Sent: Wednesday, October 21, 2015 05:27To: iiordanov/remote-desktop-clientsReply To: iiordanov/remote-desktop-clientsSubject: [remote-desktop-clients] how to build aspice in Android studio  (#62)hi，how to build aspice in Android studio in windows 7

—Reply to this email directly or view it on GitHub.

**Comment by edsgershao** [comment]
how to build aspice in Android studio,  how to build llibgstreamer_android.so and libspice.so ?
