### ISSUE TITLE
Hacker's Keyboard Ctrl + Shift + <key> activates the "change language" shortcut of Ctrl + Shift - doesn't happen in Jump Desktop VNC

### ISSUE THREAD

**Issue by JeffKang** [iiordanov/remote-desktop-clients#73]
Hacker's Keyboard

> Are you missing the key layout you're used to from your computer?
> This keyboard has separate number keys, punctuation in the usual places, and arrow keys.
> It is based on the AOSP Gingerbread soft keyboard, so it supports multitouch for the modifier keys.

https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard&hl=en

If you press Ctrl, Shift, and then [key], bVNC mistakenly activates the "Change Between Keyboard Input Languages" shortcut of Ctrl + Shift.
With partial success, the Jump Desktop VNC app can do Ctrl + Shift + [key].

For just Ctrl, and then [key], the shortcuts are reliable in bVNC.
Jump Desktop VNC has problems with Ctrl.

**Comment by iiordanov** [comment]
I cannot reproduce this on any device with Android 5 and 6, connecting to x11vnc on Linux.                                                                                                                                                                                                                                                                                                                                        --The conscious mind has only one thread of execution.                                                                                                                                                                                                                From: Jeff KangSent: Wednesday, August 10, 2016 20:53To: iiordanov/remote-desktop-clientsReply To: iiordanov/remote-desktop-clientsSubject: [iiordanov/remote-desktop-clients] Hacker's Keyboard Ctrl + Shift + <key> activates the "change language" shortcut of Ctrl + Shift - doesn't happen in Jump VNC (#73)Hacker's Keyboard


Are you missing the key layout you're used to from your computer?
This keyboard has separate number keys, punctuation in the usual places, and arrow keys.
It is based on the AOSP Gingerbread soft keyboard, so it supports multitouch for the modifier keys.


https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard&hl=en

If you press Ctrl, Shift, and then [key], bVNC mistakenly activates the "Change Between Keyboard Input Languages" shortcut of Ctrl + Shift.
With partial success, the Jump Desktop VNC app can do Ctrl + Shift + [key].

For just Ctrl, and then [key], the shortcuts are reliable in bVNC.
Jump Desktop VNC has problems with Ctrl.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iiordanov/remote-desktop-clients","title":"iiordanov/remote-desktop-clients","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iiordanov/remote-desktop-clients"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Hacker's Keyboard Ctrl + Shift + \u003ckey\u003e activates the \"change language\" shortcut of Ctrl + Shift - doesn't happen in Jump VNC (#73)"}],"action":{"name":"View Issue","url":"https://github.com/iiordanov/remote-desktop-clients/issues/73"}}}

**Comment by JeffKang** [comment]
>Linux

Hmm.. I'm using bVNC Pro with Windows 10.
E.g.
I want to open the bookmark manager in Chrome.
I press Ctrl, Shift, and as soon as I press o, ENG US switches to the next language, which is ENG CAFR (English Canadian French).
Jump Desktop VNC works normally, and activates the bookmark manager.

Edit: Problem bypassed:
I disabled the Ctrl + Shift shortcut.
Control Panel -> Language -> Advanced settings -> Change language bar hot keys -> Change key sequence.

**Comment by iiordanov** [comment]
Is this still an issue?

**Comment by iiordanov** [comment]
I cannot reproduce this with the latest Hacker's Keyboard from Google Play and bVNC v5.0.9. Please ask to reopen if you still see this issue.

**Comment by JeffKang** [comment]
Not sure, very long ago. You can close.
