### ISSUE TITLE
No AbstractConnectionBean

### ISSUE THREAD

**Issue by wytrzeszcz** [iiordanov/remote-desktop-clients#74]
Hi, i need to make launcher from your app bVNC.
Now I'm trying to compile it in Android Stiudio but I can't found AbstractConnectionBean.java file.
I'm read You say that i shoud use eclipse, but i can't install it here,
Can You push that file to repo?  or here?

**Comment by wytrzeszcz** [comment]
And after find again i can not find this legendary readme file too

**Comment by iiordanov** [comment]
What legendary readme? :) The BUILDING file?As far as Eclipse vs ADT is concerned, i also want to use ADT, but unfortunately there is an Eclipse plugin that generates this file and a bunch of other ones from some template files (the ones that start with "I").We have to either port the plugin or make the files static and maintain them by hand.‎I can attach the current version of the files to this issue or even push them into a separate directory in the repo if you like, but they will go out of date.Iordan                                                                                                                                                                                                   --The conscious mind has only one thread of execution.                                                                                                                                                                                                                From: wytrzeszczSent: Thursday, August 11, 2016 03:01To: iiordanov/remote-desktop-clientsReply To: iiordanov/remote-desktop-clientsSubject: Re: [iiordanov/remote-desktop-clients] No AbstractConnectionBean (#74)And after find again i can not find this legendary readme file too

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iiordanov/remote-desktop-clients","title":"iiordanov/remote-desktop-clients","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iiordanov/remote-desktop-clients"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wytrzeszcz in #74: And after find again i can not find this legendary readme file too"}],"action":{"name":"View Issue","url":"https://github.com/iiordanov/remote-desktop-clients/issues/74#issuecomment-239087100"}}}

**Comment by Dudmahn** [comment]
Hi @iiordanov , first of all, let me congratulate you on this excellent piece of software. I've used the bVNC app from the google play store, and it looks works great against the VMLite VNC server. I'm now in the process of building bVNC from source, so that I can make some changes to the app in order to run it on a custom Android platform.  

I'm having problems relating to AbstractConnectionBean not being found. I've downloaded sqlitegen_eclipse_site_0.1.19.jar as indicated in the first step of the README file. I tried putting it in the eclipse dropins folder and restarting eclipse with the "-clean" option. I've also tried it in the plugins folder with no luck. In either case, it appears that eclipse might be ignoring the plugin. Can you provide any guidance on how to get this plugin installed into eclipse neon android?

Also, once installed, are there any additional steps that must be performed in order to generate AbstractConnectionBean? Or, will this be generated as part of the bVNC project build?

**Comment by Dudmahn** [comment]
In an attempt to figure out what's causing the problem, I've enabled the console log when starting eclipse. There are some messages about sqlitegen near the end of the log. See this attachment: 
[eclipse_log.txt](https://github.com/iiordanov/remote-desktop-clients/files/477554/eclipse_log.txt)

**Comment by Dudmahn** [comment]
@iiordanov Which version of eclipse are you using to build bVNC? Perhaps there is an incompatibility between the eclipse version and the plugin?

**Comment by iiordanov** [comment]
Hi,I would have to look, but i think it is Eclipse 3.7. You have to install the plugin from within Eclipse. I need to look at my setup to give you more in depth instructions. iordan                                                                                                                                                                                                                                                                                                                                        --The conscious mind has only one thread of execution.                                                                                                                                                                                                                From: DudmahnSent: Friday, September 16, 2016 22:27To: iiordanov/remote-desktop-clientsReply To: iiordanov/remote-desktop-clientsCc: iiordanov; MentionSubject: Re: [iiordanov/remote-desktop-clients] No AbstractConnectionBean (#74)@iiordanov Which version of eclipse are you using to build bVNC? Perhaps there is an incompatibility between the eclipse version and the plugin?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iiordanov/remote-desktop-clients","title":"iiordanov/remote-desktop-clients","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iiordanov/remote-desktop-clients"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Dudmahn in #74: @iiordanov Which version of eclipse are you using to build bVNC? Perhaps there is an incompatibility between the eclipse version and the plugin?"}],"action":{"name":"View Issue","url":"https://github.com/iiordanov/remote-desktop-clients/issues/74#issuecomment-247686015"}}}

**Comment by Dudmahn** [comment]
Thanks, please check on the eclipse version when you get a chance. In the meantime, I'll install 3.7 (Indigo) and see if that works any better.

**Comment by iiordanov** [comment]
This is no longer an issue since the switch to Android Studio.
