### ISSUE TITLE
bvnc latest version no longer connects to basic vnc through connectbot SSH tunnel

### ISSUE THREAD

**Issue by trsghub** [iiordanov/remote-desktop-clients#76]
Connection type shows "Basic VNC" 
Connection port is an local SSH forward through connectbot

It shows the message "vnc server is trying to use anonymous diffie hellman xxxx"

This used to work until very recently.  bvnc pro 3.8.4

On the server side I see the following message:

Sat Aug 27 20:47:10 2016
 Connections: accepted: 127.0.0.1::33444
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VeNCrypt(19)
 SVeNCrypt:   Client requests security type TLSVnc (258)

**Comment by iiordanov** [comment]
This is because you upgraded your device to Android 6 which does not support Diffie Hellman ciphers. Please follow the instructions bVNC gives you to disable the encryption requirement.Thanks,iordan                                                                                                                                                                                                                                                                                                                                        --The conscious mind has only one thread of execution.                                                                                                                                                                                                                From: trsghubSent: Saturday, August 27, 2016 22:00To: iiordanov/remote-desktop-clientsReply To: iiordanov/remote-desktop-clientsSubject: [iiordanov/remote-desktop-clients] bvnc latest version no longer connects to basic vnc through connectbot SSH tunnel (#76)Connection type shows "Basic VNC" 
Connection port is an local SSH forward through connectbot

It shows the message "vnc server is trying to use anonymous diffie hellman xxxx"

This used to work until very recently.  On the server side I see the following message:

Sat Aug 27 20:47:10 2016
 Connections: accepted: 127.0.0.1::33444
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VeNCrypt(19)
 SVeNCrypt:   Client requests security type TLSVnc (258)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iiordanov/remote-desktop-clients","title":"iiordanov/remote-desktop-clients","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iiordanov/remote-desktop-clients"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"bvnc latest version no longer connects to basic vnc through connectbot SSH tunnel (#76)"}],"action":{"name":"View Issue","url":"https://github.com/iiordanov/remote-desktop-clients/issues/76"}}}

**Comment by trsghub** [comment]
Thanks for the quick reply.  Sorry to waste your time.  I was laboring under the assumption that basic VNC should not do any encryption whatsoever.  

I am using an older version of tigervnc - will report back what I find out about this if anything.  It will likely be a while before I am in a position to shutdown my desktop too many client projects sitting on various desktops at the moment.  Jump VNC seems to work so I am good for the time being.

**Comment by iiordanov** [comment]
Hello, Yes, I took a look at Jump Desktop, and they ship their own OpenSSL library (the version I looked at, v5.0, had a really old unsupported OpenSSL 0.9.8r from 2011). While it will work, you should definitely tunnel that connection over SSH because it may be using out of date libraries.

To your other comment about TigerVNC, even older versions of TigerVNC should support VeNCrypt with x509 certificates that provide identity verification. I don't think you need to shut down your desktop at all to switch to that. See instructions I wrote up here:
https://groups.google.com/forum/#!topic/bvnc-ardp-aspice-opaque-android-bb10-clients/lINJkYJbN-U

**Comment by trsghub** [comment]
I finally had to restart my desktop.  I just wanted to add closure to the issue for anyone who happens upon this via search.  Please re-close this issue.

I changed my startup script by adding the securitytypes to the end.  Previously, I did not have this option:

/opt/TigerVNC/bin/vncserver -geometry 1600x900 -depth 24 -SecurityTypes=VeNCrypt,VncAuth
