### ISSUE TITLE
Generating and importing private/public keys is not working

### ISSUE THREAD

**Issue by gut5** [iiordanov/remote-desktop-clients#90]
Version is 3.8.6

**Comment by iiordanov** [comment]
You need to enter some information on the initial page (i think  ssh server ‎and ssh username are required at minimum). Otherwise your generated key will be disposed of together with the empty connection.Could that be the issue?  Without any additional information that is my guess.                                                                                                                                                                                                                                                                                                                                        --The conscious mind has only one thread of execution.                                                                                                                                                                                                                From: wrsgSent: Sunday, January 29, 2017 13:34To: iiordanov/remote-desktop-clientsReply To: iiordanov/remote-desktop-clientsCc: SubscribedSubject: [iiordanov/remote-desktop-clients] Generating and importing private/public keys is not working (#90)Version is 3.8.6

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iiordanov/remote-desktop-clients","title":"iiordanov/remote-desktop-clients","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iiordanov/remote-desktop-clients"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Generating and importing private/public keys is not working (#90)"}],"action":{"name":"View Issue","url":"https://github.com/iiordanov/remote-desktop-clients/issues/90"}}}

**Comment by wrsg** [comment]
> You need to enter some information on the initial page (i think ssh server ‎and ssh username are required at minimum). Otherwise your generated key will be disposed of together with the empty connection. Could that be the issue? Without any additional information that is my guess. 

That's definitely the issue in my case, please put a warning in because that really isn't clear at all, and sorry I know it's your app but that kind of workflow just doesn't make any sense to me at all, hope you're not offended by the criticism.

**Comment by iiordanov** [comment]
The reason for this is that due to the logic of the client bVNC was forked from in 2012, empty connections would pile up when users attempt to Manage key before entering other info.There are just so many priorities in this project‎ that i have not had time to fix this in years.Happily, this software is in use by hundreds of thousands of users, so one would presume people would flock to help fix such issues :)Sadly, that is not the case... :Diordan                                                                                                                                                                                                                                                                                                                                        --The conscious mind has only one thread of execution.                                                                                                                                                                                                                From: wrsgSent: Sunday, January 29, 2017 17:35To: iiordanov/remote-desktop-clientsReply To: iiordanov/remote-desktop-clientsCc: iiordanov; CommentSubject: Re: [iiordanov/remote-desktop-clients] Generating and importing private/public keys is not working (#90)
You need to enter some information on the initial page (i think ssh server ‎and ssh username are required at minimum). Otherwise your generated key will be disposed of together with the empty connection. Could that be the issue? Without any additional information that is my guess.

That's definitely the issue in my case, please put a warning in because that really isn't clear at all, and sorry I know it's your app but that kind of workflow just doesn't make any sense to me at all, hope you're not offended by the criticism.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iiordanov/remote-desktop-clients","title":"iiordanov/remote-desktop-clients","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iiordanov/remote-desktop-clients"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wrsg in #90: \u003e You need to enter some information on the initial page (i think ssh server ‎and ssh username are required at minimum). Otherwise your generated key will be disposed of together with the empty connection. Could that be the issue? Without any additional information that is my guess. \r\n\r\nThat's definitely the issue in my case, please put a warning in because that really isn't clear at all, and sorry I know it's your app but that kind of workflow just doesn't make any sense to me at all, hope you're not offended by the criticism."}],"action":{"name":"View Issue","url":"https://github.com/iiordanov/remote-desktop-clients/issues/90#issuecomment-275951972"}}}

**Comment by wrsg** [comment]
I will attempt it if that's any consolation :)

**Comment by iiordanov** [comment]
Sounds great! :)Thanks!iordan                                                                                                                                                                                                                                                                                                                                        --The conscious mind has only one thread of execution.                                                                                                                                                                                                                From: wrsgSent: Sunday, January 29, 2017 17:45To: iiordanov/remote-desktop-clientsReply To: iiordanov/remote-desktop-clientsCc: iiordanov; CommentSubject: Re: [iiordanov/remote-desktop-clients] Generating and importing private/public keys is not working (#90)I will attempt it if that's any consolation :)

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iiordanov/remote-desktop-clients","title":"iiordanov/remote-desktop-clients","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iiordanov/remote-desktop-clients"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wrsg in #90: I will attempt it if that's any consolation :) "}],"action":{"name":"View Issue","url":"https://github.com/iiordanov/remote-desktop-clients/issues/90#issuecomment-275952689"}}}
