### ISSUE TITLE
Touch click event

### ISSUE THREAD

**Issue by zhuowr2006** [iiordanov/remote-desktop-clients#97]
Hello，When I click on the screen in the spice, there will be two touch events, and directly into the virtual machine inside. Where can I change this setting?

**Comment by iiordanov** [comment]
Hey,You are probably seeing a mouse button down followed by a mouse button up event.Alternatively, your device is detecting a double click erroneously, but i have never seen that.iordan                                                                                                                                                                                                                                                                                                                                        --The conscious mind has only one thread of execution.                                                                                                                                                                                                                From: zhuowr2006Sent: Friday, March 31, 2017 03:50To: iiordanov/remote-desktop-clientsReply To: iiordanov/remote-desktop-clientsCc: SubscribedSubject: [iiordanov/remote-desktop-clients] Touch click event (#97)Hello，When I click on the screen in the spice, there will be two touch events, and directly into the virtual machine inside. Where can I change this setting?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iiordanov/remote-desktop-clients","title":"iiordanov/remote-desktop-clients","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iiordanov/remote-desktop-clients"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Touch click event (#97)"}],"action":{"name":"View Issue","url":"https://github.com/iiordanov/remote-desktop-clients/issues/97"}}}

**Comment by zhuowr2006** [comment]
![gif](https://cloud.githubusercontent.com/assets/17844925/24574438/2aa64e6c-16c5-11e7-8ebf-b3015911f5ed.gif)      
  
Like this，Every time you click, it will trigger a two click event。Continuous click will only repeat the last click event

**Comment by iiordanov** [comment]
This is no longer causing issues, right?
